function initialize(){
const $=id=>document.getElementById(id), bridge=window.AstrBotPluginPage;
const node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};
const sharing={personal:'个人',project:'项目',team:'团队'};let rows=[];
async function mutation(payload){await bridge.apiPost('manage',payload);await refresh();}
function render(){const list=$('skills');list.replaceChildren();const q=$('query').value.trim().toLowerCase();
const filtered=rows.filter(r=>{const m=r.metadata;return (!q||JSON.stringify(r).toLowerCase().includes(q))&&['category','platform','project','sharing'].every(k=>!$(k).value||m[k]===$(k).value)&&(!$('active').value||String(r.active)===$('active').value);});
for(const r of filtered){const m=r.metadata,card=node('article','');card.append(node('h2',m.title),node('p',m.description||r.name));
const tags=node('p','');for(const t of [m.category,m.platform||'不限平台',m.project||'不限项目',sharing[m.sharing],r.active?'已启用':'已停用',`v${r.version}`])tags.append(node('span',t));for(const t of tags.children)t.className='tag';card.append(tags,node('small',`创建人 ${r.owner} · 更新 ${r.created} · ${r.id}`));
const actions=node('div','');actions.className='actions';const toggle=node('button',r.active?'停用':'恢复');toggle.onclick=async()=>{toggle.disabled=true;try{await mutation({id:r.id,action:r.active?'disable':'enable',expected_version:r.version});}catch(e){$('notice').textContent=e.message||'操作失败，请刷新';toggle.disabled=false;}};actions.append(toggle);card.append(actions);
const detail=node('details','');detail.append(node('summary','查看正文、版本、分组与反馈'));let loaded=false;detail.ontoggle=async()=>{if(!detail.open||loaded)return;try{const d=await bridge.apiPost('detail',{id:r.id});if(d.skill.version!==r.version){$('notice').textContent='记录已更新，请刷新后管理';return;}loaded=true;
detail.append(node('pre',d.skill.body));const form=node('form','');const fields={};for(const [key,title] of Object.entries({title:'标题',category:'分类',platform:'适用平台（空为不限）',project:'适用项目（空为不限）',sharing:'共享范围',maintainers:'维护者 Open ID（逗号分隔）'})){const label=node('label',title),input=node(key==='sharing'?'select':'input','');if(key==='sharing'){for(const [v,t]of Object.entries(sharing)){const o=node('option',t);o.value=v;input.append(o);}}input.value=key==='maintainers'?m[key].join(','):m[key];fields[key]=input;label.append(input);form.append(label);}const submit=node('button','保存分组与共享');submit.className='primary';submit.type='submit';form.append(submit);form.onsubmit=async ev=>{ev.preventDefault();submit.disabled=true;try{const metadata={...m};for(const k of Object.keys(fields))metadata[k]=k==='maintainers'?fields[k].value.split(',').map(x=>x.trim()).filter(Boolean):fields[k].value.trim();await mutation({id:r.id,action:'metadata',expected_version:r.version,metadata});}catch(e){$('notice').textContent=e.message||'保存失败';submit.disabled=false;}};detail.append(form,node('h3','版本记录'));
for(const v of d.versions){const line=node('p',`v${v.version} · ${v.created} · ${v.actor} `);if(v.version!==r.version&&r.active){const b=node('button','恢复此版本正文');b.onclick=async()=>{b.disabled=true;try{await mutation({id:r.id,action:'rollback',expected_version:r.version,version:v.version});}catch(e){$('notice').textContent=e.message||'回滚失败';b.disabled=false;}};line.append(b);}detail.append(line);}detail.append(node('p','回滚产生新版本；保留当前共享范围，避免恢复旧权限。'),node('h3','建议与使用反馈'));for(const e of d.events)detail.append(node('p',`${e.created} · ${e.actor} · ${e.kind}：${e.content}`));if(!d.events.length)detail.append(node('p','暂无反馈。'));
}catch(e){$('notice').textContent=e.message||'读取详情失败';}};card.append(detail);list.append(card);}
if(!filtered.length){const empty=node('p','还没有匹配的 Skill。在聊天中引用已确认的方法，发送“保存为团队 Skill”，并说明分类、平台和共享范围。');empty.className='empty';list.append(empty);}}
async function refresh(){try{const result=await bridge.apiGet('catalog');rows=result.skills;const pending=$('deliveries');pending.replaceChildren();for(const d of result.deliveries||[]){const line=node('p',`${d.created} · ${d.actor} · ${d.id}`);for(const [kind,r] of Object.entries(d.parts)){line.append(node('p',`${kind==='skill'?'Skill':'项目知识'}：${['saved','installed'].includes(r.status)?'已完成':'未完成'} ${r.message||''}`));}pending.append(line);}if(!(result.deliveries||[]).length)pending.append(node('p','暂无保存任务。'));for(const key of ['category','platform','project']){const select=$(key),prev=select.value;select.replaceChildren();const all=node('option',`全部${{category:'分类',platform:'平台',project:'项目'}[key]}`);all.value='';select.append(all);for(const value of [...new Set(rows.map(r=>r.metadata[key]).filter(Boolean))].sort()){const o=node('option',value);o.value=value;select.append(o);}select.value=prev;}render();$('notice').textContent=`共 ${rows.length} 个团队管理 Skill。原生内置技能仍在 AstrBot 技能页查看。`;}catch(e){$('notice').textContent=e.message||'加载失败，请重试';}}
for(const id of ['query','category','platform','project','sharing','active'])$(id).oninput=render;$('refresh').onclick=refresh;(async()=>{try{await bridge.ready();await refresh();}catch(e){$('notice').textContent='请从 AstrBot 插件页面打开';}})();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initialize,{once:true});else initialize();
